### ISSUE TITLE
silent crash on launch

### ISSUE THREAD

**Issue by sat3ll** [flathub/org.clementine_player.Clementine#11]
This app (which used to work fine until a few weeks ago), is now crashing with:
> ... (lines omitted)
>
> 01:41:28.847 DEBUG MainWindow:979                   Loading settings
> 01:41:28.849 INFO  NetworkRemote:83                 Network Remote deactivated
> __logging_message__01:41:28.850 WARN  unknown                          env says KDE is running but SNI unavailable -- check KDE_FULL_SESSION and XDG_CURRENT_DESKTOP
> 01:41:28.881 DEBUG MainWindow:2206                  command line options received
> 01:41:28.881 DEBUG MainWindow:2287                  false
> 01:41:28.933 DEBUG MainWindow:1069                  Started
> 01:41:28.997 DEBUG PlaylistBackend:292              Saving playlist 2
> 01:41:29.297 DEBUG PlaylistBackend:292              Saving playlist 3
> 01:41:29.355 DEBUG PlaylistBackend:292              Saving playlist 5
> 01:41:29.417 DEBUG PlaylistBackend:292              Saving playlist 4
> 01:41:29.481 DEBUG PlaylistBackend:292              Saving playlist 1
> /usr/include/c++/8.2.0/bits/stl_vector.h:950: std::vector<_Tp, _Alloc>::const_reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) const [with _Tp = float; _Alloc = std::allocator<float>; std::vector<_Tp, _Alloc>::const_reference = const float&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
> 

Note that now the window doesn't even appear, crashing instantly on app launch.
I've tried bumping the git revision of Clementine up but unfortunately they've made some change that ends up not detecting 'qjson' module that is built by flatpak during the build process.

**Comment by FakeShemp** [comment]
I'm not experiencing the same problem on my end but I've made a PR which updates all components to their latest versions. If you could try the test build there and see if it makes any difference, that would be great.

You can install it with
`flatpak install --user https://dl.flathub.org/build-repo/3588/org.clementine_player.Clementine.flatpakref
`

**Comment by sat3ll** [comment]
Same message unfortunately:
> /usr/include/c++/8.3.0/bits/stl_vector.h:950: std::vector<_Tp, _Alloc>::const_reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) const [with _Tp = float; _Alloc = std::allocator<float>; std::vector<_Tp, _Alloc>::const_reference = const float&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.

**Comment by sat3ll** [comment]
Seems like something's up with my .var/app/org.clementine.Clementine folder. Deleting this and allowing it to be remade fixed it (bug with Clementine?)

**Comment by FakeShemp** [comment]
It's probably a Clementine issue. I once had a playlist which had corrupted some and that stopped Clementine from launching as well.

Thank you very much for reporting and testing, though.
