### ISSUE TITLE
Tray icon does not work

### ISSUE THREAD

**Issue by FakeShemp** [flathub/org.clementine_player.Clementine#17]
It just doesn't show up

**Comment by gasinvein** [comment]
This probably could be fixed by adding `--talk-name=org.kde.StatusNotifierWatcher` and `--own-name=org.kde.StatusNotifierItem-2-2` permissions. Not sure if it's the right way, but it should work.

**Comment by FakeShemp** [comment]
Thanks again :) That `StatusNotifierItem-2-2` threw me off completely when I tried to solve it.
