### ISSUE TITLE
Clementine qt5 won't start in wayland sessions

### ISSUE THREAD

**Issue by mikelpr** [flathub/org.clementine_player.Clementine#30]
it stops at DEBUG QxtGlobalShortcutBackend:32      registering

I think #27 refers to this
but as of april 2020 it still is a bug, even as #28 supposedly fixed it. I have my flatpaks up to date so there's been no new build I suppose?

**Comment by FakeShemp** [comment]
Wayland socket removed in 40c367ac859602dffba94040aacbea0e18e4a3c5
