### ISSUE TITLE
Make this the Qt4 version?

### ISSUE THREAD

**Issue by FakeShemp** [flathub/org.clementine_player.Clementine#6]
With Flathub now supporting beta builds, do you users of Clementine think it is a good idea to downgrade this repo to the main Qt4 master branch (1.3.1) and make the Qt5 branch a beta build instead?

**Comment by TingPing** [comment]
I'd say no. Qt4 is dead and just makes the Flatpak user experience worse.

**Comment by nedrichards** [comment]
Agreed with @TingPing also, downgrades are rarely a good thing for existing users. Settings etc. don't often anticipate going backwards and it's rarely tested.
