### ISSUE TITLE
clementine: error while loading shared libraries

### ISSUE THREAD

**Issue by rvlobato** [flathub/org.clementine_player.Clementine#9]
clementine: error while loading shared libraries: libaom.so.0: cannot open shared object file: No such file or directory

Flatpak version 1.2.4
Shared libraries used by KDE applications 5.12

**Comment by FakeShemp** [comment]
When does this happen?

**Comment by nedrichards** [comment]
That issue is https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/709 when it's fixed in the SDK it'll be fixed everywhere. Apologies.

**Comment by mr-falafel** [comment]
I've been experiencing issues similar to this with flatpak apps, unfortunately regularly. I'm sure it isn't anybody's fault but it is very frustrating. :/

**Comment by Erick555** [comment]
@mr-falafel you may try [workaround](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/709#note_155468291) until it's fixed.

**Comment by Erick555** [comment]
@mr-falafel @rvlobato  the fix was published on flathub. Everything should work after `flatpak update`.

**Comment by mr-falafel** [comment]
Yay! I'm glad it's fixed, now. It would be nice if there was a way to prevent things like this from happening.
